let three = 3
console.log(1)
console.log(2)
try{
  console.log(three)
}catch(error){
  console.log(error)
}
console.log(4)